/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import FordFulkerson.MaxFlow;
import GrafoRandomico.GrafoRando;
import Variaveis.grafo;
import arquivosTxt.leitura;
import java.awt.CardLayout;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author anderson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    grafo var = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        EscCidades = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCidades = new javax.swing.JTextArea();
        CBcidade1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CBcidade2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnNext2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArestas = new javax.swing.JTextArea();
        EntGrafo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SNcidades = new javax.swing.JSpinner();
        SNminTon = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        SNmaxTon = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btncarTxt = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        SNarestas = new javax.swing.JSpinner();
        Resultado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSolucoes = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lResultado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnNSim = new javax.swing.JButton();
        btnNGrafo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        CarregarTxt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCaminho = new javax.swing.JTextField();
        btnCaminho = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        RBGorientado = new javax.swing.JRadioButton();
        RBGnorientado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Base.setLayout(new java.awt.CardLayout());

        txtCidades.setColumns(20);
        txtCidades.setRows(5);
        jScrollPane1.setViewportView(txtCidades);

        CBcidade1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cidade de origem");

        CBcidade2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cidade de detino");

        btnNext2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btnNext2.setText("Gerar rotas");
        btnNext2.setToolTipText("");
        btnNext2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cidades");

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Arestas");

        txtArestas.setColumns(20);
        txtArestas.setRows(5);
        jScrollPane3.setViewportView(txtArestas);

        javax.swing.GroupLayout EscCidadesLayout = new javax.swing.GroupLayout(EscCidades);
        EscCidades.setLayout(EscCidadesLayout);
        EscCidadesLayout.setHorizontalGroup(
            EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscCidadesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscCidadesLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EscCidadesLayout.createSequentialGroup()
                        .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EscCidadesLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBcidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBcidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscCidadesLayout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))))))
        );
        EscCidadesLayout.setVerticalGroup(
            EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscCidadesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscCidadesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGroup(EscCidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EscCidadesLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(EscCidadesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))))
                    .addGroup(EscCidadesLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBcidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBcidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Base.add(EscCidades, "DefCidades");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel4.setText("Numero de cidades:");

        SNcidades.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        SNcidades.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));

        SNminTon.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        SNminTon.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel5.setText("Valor minimo de toneladas:");

        SNmaxTon.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        SNmaxTon.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel6.setText("Valor maximo de toneladas:");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gerar Grafo");

        btncarTxt.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btncarTxt.setText("Carregar Txt");
        btncarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarTxtActionPerformed(evt);
            }
        });

        btnGerar.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel13.setText("Numero de arestas:");

        SNarestas.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        SNarestas.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        javax.swing.GroupLayout EntGrafoLayout = new javax.swing.GroupLayout(EntGrafo);
        EntGrafo.setLayout(EntGrafoLayout);
        EntGrafoLayout.setHorizontalGroup(
            EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntGrafoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btncarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(EntGrafoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntGrafoLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EntGrafoLayout.createSequentialGroup()
                        .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EntGrafoLayout.createSequentialGroup()
                                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SNmaxTon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SNminTon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SNarestas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SNcidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EntGrafoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(137, Short.MAX_VALUE))))
        );
        EntGrafoLayout.setVerticalGroup(
            EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntGrafoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNcidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNminTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNmaxTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNarestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(EntGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        Base.add(EntGrafo, "entGrafo");

        txtSolucoes.setColumns(20);
        txtSolucoes.setRows(5);
        jScrollPane2.setViewportView(txtSolucoes);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        jLabel8.setText("Resultados");

        lResultado.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        lResultado.setText("Resul");

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel12.setText("Outras possiveis soluções:");

        btnNSim.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btnNSim.setText("Nova Simulação");
        btnNSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNSimActionPerformed(evt);
            }
        });

        btnNGrafo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btnNGrafo.setText("Novo Grafo");
        btnNGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGrafoActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btnExit.setText("Sair");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultadoLayout = new javax.swing.GroupLayout(Resultado);
        Resultado.setLayout(ResultadoLayout);
        ResultadoLayout.setHorizontalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ResultadoLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ResultadoLayout.createSequentialGroup()
                                .addComponent(btnNSim, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnNGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lResultado)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ResultadoLayout.setVerticalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addComponent(lResultado)
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNSim, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Base.add(Resultado, "resultados");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setText("Caminho do arquivo");

        txtCaminho.setEditable(false);
        txtCaminho.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        btnCaminho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Open-file-icon.png"))); // NOI18N
        btnCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminhoActionPerformed(evt);
            }
        });

        btnNext1.setBackground(java.awt.Color.lightGray);
        btnNext1.setFont(new java.awt.Font("DejaVu Sans", 1, 28)); // NOI18N
        btnNext1.setText("Proximo");
        btnNext1.setToolTipText("");
        btnNext1.setBorder(null);
        btnNext1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        RBGorientado.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        RBGorientado.setText("Grafo Orientado");
        RBGorientado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBGorientadoActionPerformed(evt);
            }
        });

        RBGnorientado.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        RBGnorientado.setText("Grafo não Orietado");
        RBGnorientado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBGnorientadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarregarTxtLayout = new javax.swing.GroupLayout(CarregarTxt);
        CarregarTxt.setLayout(CarregarTxtLayout);
        CarregarTxtLayout.setHorizontalGroup(
            CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarregarTxtLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarregarTxtLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CarregarTxtLayout.createSequentialGroup()
                                .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78))
                    .addGroup(CarregarTxtLayout.createSequentialGroup()
                        .addGroup(CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(CarregarTxtLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(RBGorientado)
                                .addGap(190, 190, 190)
                                .addComponent(RBGnorientado)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        CarregarTxtLayout.setVerticalGroup(
            CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarregarTxtLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCaminho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(CarregarTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBGorientado)
                    .addComponent(RBGnorientado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        Base.add(CarregarTxt, "CarTxt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CardLayout card = (CardLayout) Base.getLayout();
        card.show(Base, "entGrafo");
    }//GEN-LAST:event_formWindowOpened

    private void btnCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminhoActionPerformed
        JFileChooser fc = new JFileChooser();
        int opcao = fc.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION)        txtCaminho.setText(fc.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_btnCaminhoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        leitura cartxt = new leitura();
        try {
            if((var = cartxt.lerArquivo(txtCaminho.getText())) != null){
                ControleTela ct = new ControleTela();
                ct.preencherCampor1(this, var);
                CardLayout card = (CardLayout) Base.getLayout();
                card.show(Base, "DefCidades");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnNSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNSimActionPerformed
        CardLayout card = (CardLayout) Base.getLayout();
        card.show(Base, "DefCidades");
    }//GEN-LAST:event_btnNSimActionPerformed

    private void btnNGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGrafoActionPerformed
        CardLayout card = (CardLayout) Base.getLayout();
        card.show(Base, "entGrafo");
    }//GEN-LAST:event_btnNGrafoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btncarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarTxtActionPerformed
        CardLayout card = (CardLayout) Base.getLayout();
        card.show(Base, "CarTxt");
    }//GEN-LAST:event_btncarTxtActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        if(this.CBcidade1.getSelectedIndex() != this.CBcidade2.getSelectedIndex()){
            if(var.mGrafo[this.CBcidade1.getSelectedIndex()][this.CBcidade2.getSelectedIndex()] < 0){
                JOptionPane.showMessageDialog(null, "Não possui rota entre essas cidades", "Alerta", JOptionPane.WARNING_MESSAGE);
                var.txtResul = "Não possui rota entre essas cidades, tente outra rota";
            }else{
                MaxFlow m = new MaxFlow(var.getTam());
                var.txtResul = "O fluxo maximo entre " + var.nCidades[this.CBcidade1.getSelectedIndex()] + " e " + 
                                var.nCidades[this.CBcidade2.getSelectedIndex()] + " é " + 
                                m.fordFulkerson(var.mGrafo, this.CBcidade1.getSelectedIndex(), this.CBcidade2.getSelectedIndex()) + " toneladas.";
            }
            ControleTela ct = new ControleTela();
            ct.sugestoes(this, var, this.CBcidade1.getSelectedIndex(), this.CBcidade2.getSelectedIndex());
            CardLayout card = (CardLayout) Base.getLayout();
            card.show(Base, "resultados");
        }else{
            JOptionPane.showMessageDialog(null, "Cidade de saida é a mesma de chegada", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void RBGorientadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBGorientadoActionPerformed

    }//GEN-LAST:event_RBGorientadoActionPerformed

    private void RBGnorientadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBGnorientadoActionPerformed

    }//GEN-LAST:event_RBGnorientadoActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        if((int) this.SNarestas.getValue() >= (int) this.SNcidades.getValue()){
            if((int) this.SNmaxTon.getValue() > (int) this.SNminTon.getValue()){
                GrafoRando gr = new GrafoRando();
                ControleTela ct = new ControleTela();
                var = gr.GrafoR((int) this.SNcidades.getValue(),(int) this.SNminTon.getValue(),(int) this.SNmaxTon.getValue(),(int) this.SNarestas.getValue());
                ct.preencherCampor1(this, var);
                CardLayout card = (CardLayout) Base.getLayout();
                card.show(Base, "DefCidades");
            }
            else{
                JOptionPane.showMessageDialog(null, "Valor de maxima de toneladas necessita ser maior que o valor minimo de toneladas.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Numero de arestas necessita ser maior ou igual ao número de cidades.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Base;
    public javax.swing.JComboBox<String> CBcidade1;
    public javax.swing.JComboBox<String> CBcidade2;
    public javax.swing.JPanel CarregarTxt;
    public javax.swing.JPanel EntGrafo;
    public javax.swing.JPanel EscCidades;
    public javax.swing.JRadioButton RBGnorientado;
    public javax.swing.JRadioButton RBGorientado;
    public javax.swing.JPanel Resultado;
    public javax.swing.JSpinner SNarestas;
    public javax.swing.JSpinner SNcidades;
    public javax.swing.JSpinner SNmaxTon;
    public javax.swing.JSpinner SNminTon;
    public javax.swing.JButton btnCaminho;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnGerar;
    public javax.swing.JButton btnNGrafo;
    public javax.swing.JButton btnNSim;
    public javax.swing.JButton btnNext1;
    public javax.swing.JButton btnNext2;
    public javax.swing.JButton btncarTxt;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lResultado;
    public javax.swing.JTextArea txtArestas;
    public javax.swing.JTextField txtCaminho;
    public javax.swing.JTextArea txtCidades;
    public javax.swing.JTextArea txtSolucoes;
    // End of variables declaration//GEN-END:variables
}
